#!/usr/bin/env python
# -*- coding: utf-8 -*-
# ====================================================================================================================================================
# 
# 此文件用于定义 ContentForge 项目的命令行接口（CLI）入口及相关命令的加载
#
# 本文件负责将项目中的各个命令模块动态加载到 CLI 中，以便用户能够通过命令行执行相应操作。
# 具体功能包括：
# 1. 设置 CLI 入口
# 2. 动态加载位于 contentforge.utils.command 模块中的命令
#
# @filename   artisan
# @path       artisan
# @project    ContentForge
# @encoding   utf-8
#
# @product    PyCharm
# @author     Carl Chen
# @email      mailto:ContentForge.org@hotmail.com
# @time       2024/12/8 00:57
#
# @version    git
# @record     2024/12/8 0:57 <Carl Chen> Create file.
#             2024/12/8 0:57 <Carl Chen> Update header comment.
#             CURRENT_USER_NAME description
#
# @license    http://www.opensource.org/licenses/mit-license.html  MIT License
#
# @copyright  Copyright (c) 2024. All rights reserved.
#
#             This software, including its code, documentation, and related materials,
#             is protected by copyright law and international treaties.
#             Unauthorized use, reproduction, or distribution of any part of this software is prohibited.
#
#             ContentForge is a trademark of ContentForge.org.
#             All other trademarks and registered trademarks are the property of their respective owners.
#
#             For permissions, please contact ContentForge.org@hotmail.com.
# ====================================================================================================================================================
from __future__ import print_function, unicode_literals

# =============================================================================================================
# Standard Python Imports
# =============================================================================================================
import importlib
import os
import pkgutil
import sys

import click

# 将 utils 路径加入 sys.path
current_dir = os.path.dirname(os.path.abspath(__file__))  # 获取当前文件目录
utils_path = os.path.join(current_dir, 'vendor', 'contentforge', 'utils')
sys.path.insert(0, os.path.join(current_dir, 'vendor'))

# 导入 contentforge.utils 命令模块
from contentforge.utils import command


@click.group()
def cli():
    """
    ContentForge 命令行工具

    该工具用于执行 ContentForge 项目中的各种命令。

    示例用法：
        python artisan <command> [options]
    """
    pass


def load_commands():
    """

    动态加载位于 contentforge.utils.command 模块中的命令

    该函数遍历 command 包内的所有模块，并检查每个模块是否包含名为 'cli' 的命令。如果存在，则将该命令添加到主 CLI 入口。
    这样，所有在 contentforge.utils.command 中定义的命令模块都会被自动加载到 CLI 中。

    使用示例：
        load_commands()
    """
    for _, module_name, _ in pkgutil.iter_modules(command.__path__):
        # 动态加载模块
        module = importlib.import_module(f"vendor.contentforge.utils.command.{module_name}")
        # 如果模块中定义了 'cli' 命令，则将其添加到 CLI
        if hasattr(module, 'cli'):
            cli.add_command(module.cli, name=module_name)


# 调用加载命令的函数
load_commands()

# =============================================================================================================
# Script Execution
# =============================================================================================================
if __name__ == '__main__':
    # 执行命令行工具
    cli()
