name: Publish Package to PyPI

on:
  push:
    tags:
      - 'v*'  # Trigger publishing for tags starting with v

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry and Build Package
        run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry install
          poetry build

      - name: Publish to PyPI
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: poetry publish --username $PYPI_USERNAME --password $PYPI_PASSWORD
